package com.individual.paternity_test_system;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ErrorMessage implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Error Message")
	private java.lang.String errorMessage;

	public ErrorMessage() {
	}

	public java.lang.String getErrorMessage() {
		return this.errorMessage;
	}

	public void setErrorMessage(java.lang.String errorMessage) {
		this.errorMessage = errorMessage;
	}

	public ErrorMessage(java.lang.String errorMessage) {
		this.errorMessage = errorMessage;
	}

}