package com.individual.paternity_test_system;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TestApplication implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Testee")
	private com.individual.paternity_test_system.Person testee;
	@org.kie.api.definition.type.Label("Father")
	private com.individual.paternity_test_system.Person father;
	@org.kie.api.definition.type.Label("Mother")
	private com.individual.paternity_test_system.Person mother;
	@org.kie.api.definition.type.Label("Height Factor")
	private double heightFactor;
	@org.kie.api.definition.type.Label("Blood Factor")
	private double bloodFactor;
	@org.kie.api.definition.type.Label("Hair Factor")
	private double hairFactor;
	@org.kie.api.definition.type.Label("Possibility")
	private double possibility;
	@org.kie.api.definition.type.Label("Result")
	private java.lang.String result;

	@org.kie.api.definition.type.Label(value = "Error Message")
	private com.individual.paternity_test_system.ErrorMessage errorMessage;

	public TestApplication() {
	}

	public com.individual.paternity_test_system.Person getTestee() {
		return this.testee;
	}

	public void setTestee(com.individual.paternity_test_system.Person testee) {
		this.testee = testee;
	}

	public com.individual.paternity_test_system.Person getFather() {
		return this.father;
	}

	public void setFather(com.individual.paternity_test_system.Person father) {
		this.father = father;
	}

	public com.individual.paternity_test_system.Person getMother() {
		return this.mother;
	}

	public void setMother(com.individual.paternity_test_system.Person mother) {
		this.mother = mother;
	}

	public double getHeightFactor() {
		return this.heightFactor;
	}

	public void setHeightFactor(double heightFactor) {
		this.heightFactor = heightFactor;
	}

	public double getBloodFactor() {
		return this.bloodFactor;
	}

	public void setBloodFactor(double bloodFactor) {
		this.bloodFactor = bloodFactor;
	}

	public double getHairFactor() {
		return this.hairFactor;
	}

	public void setHairFactor(double hairFactor) {
		this.hairFactor = hairFactor;
	}

	public double getPossibility() {
		return this.possibility;
	}

	public void setPossibility(double possibility) {
		this.possibility = possibility;
	}

	public java.lang.String getResult() {
		return this.result;
	}

	public void setResult(java.lang.String result) {
		this.result = result;
	}

	public com.individual.paternity_test_system.ErrorMessage getErrorMessage() {
		return this.errorMessage;
	}

	public void setErrorMessage(
			com.individual.paternity_test_system.ErrorMessage errorMessage) {
		this.errorMessage = errorMessage;
	}

	public TestApplication(com.individual.paternity_test_system.Person testee,
			com.individual.paternity_test_system.Person father,
			com.individual.paternity_test_system.Person mother,
			double heightFactor, double bloodFactor, double hairFactor,
			double possibility, java.lang.String result,
			com.individual.paternity_test_system.ErrorMessage errorMessage) {
		this.testee = testee;
		this.father = father;
		this.mother = mother;
		this.heightFactor = heightFactor;
		this.bloodFactor = bloodFactor;
		this.hairFactor = hairFactor;
		this.possibility = possibility;
		this.result = result;
		this.errorMessage = errorMessage;
	}

}